### ISSUE TITLE
Add a function to create a copy to clipboard input

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-ALToolbox#16]
Here is a hardcoded one that is not quite right yet:

```yaml
fields:
  - note: |
      Copy and share this link
      <input disabled="true" type="text" value="${ interview_url(i=user_info().filename, style="short", new_session=1) }" id="myInput">
      <div class="copy-tooltip">
      <button onclick="myFunction()" onmouseout="outFunc()" type="button">
        <span class="tooltiptext" id="myTooltip">Copy to clipboard</span>
        <i class="far fa-copy"></i>
        </button>
      </div>      
script: |
  <script>
    function myFunction() {
      var copyText = document.getElementById("myInput");
      copyText.select();
      copyText.setSelectionRange(0, 99999);
      document.execCommand("copy");

      var tooltip = document.getElementById("myTooltip");
      tooltip.innerHTML = "Copied: " + copyText.value;
    }

    function outFunc() {
      var tooltip = document.getElementById("myTooltip");
      tooltip.innerHTML = "Copy to clipboard";
    }
  </script>
css: |
  <style>
  .copy-tooltip {
    position: relative;
    display: inline-block;
  }

  .copy-tooltip .tooltiptext {
    visibility: hidden;
    width: 140px;
    background-color: #555;
    color: #fff;
    text-align: center;
    border-radius: 6px;
    padding: 5px;
    position: absolute;
    z-index: 1;
    bottom: 150%;
    left: 50%;
    margin-left: -75px;
    opacity: 0;
    transition: opacity 0.3s;
  }

  .copy-tooltip .tooltiptext::after {
    content: "";
    position: absolute;
    top: 100%;
    left: 50%;
    margin-left: -5px;
    border-width: 5px;
    border-style: solid;
    border-color: #555 transparent transparent transparent;
  }

  .copy-tooltip:hover .tooltiptext {
    visibility: visible;
    opacity: 1;
  }
  </style>
```

@plocket is this up your alley?

**Comment by nonprofittechy** [comment]
Goals: have one function that works for multiple inputs on the same screen.

Get the copy button aligned on the same horizontal plane as the input.

Make the button look more like the Bootstrap buttons

**Comment by plocket** [comment]
Is this whole thing one unit that will always appear this way? That is, `Copy and share this link <input> <button>`.

If not, what will be consistent about this? For example, will the 'Share' button always be inline?

**Comment by nonprofittechy** [comment]
I think the "copy" button will always be on the same horizontal plane as the input. Is that what you mean? I think it's just one indivisible unit.

**Comment by nonprofittechy** [comment]
We could add CSS and JS files to be included. the function should generate the input, the tooltip, and the copy button, and allow you to have multiples on the screen.

**Comment by plocket** [comment]
Provided two branches with two different behaviors.

Does not allow interaction with the input field, but the input field is visible: https://github.com/SuffolkLITLab/docassemble-ALToolbox/compare/16share

Additionally hides input field under button: https://github.com/SuffolkLITLab/docassemble-ALToolbox/compare/16_share_hidden

More work needs to be done to separate concerns and improve some names, so let me know which you prefer.

**Comment by nonprofittechy** [comment]
I think it's better for transparency (and in case someone has trouble interacting with the button) if we show the text that will be copied. So let's keep developing that branch. Thanks! Looking good so far.

**Comment by plocket** [comment]
Got it. What arguments is the function supposed to accept?

**Comment by nonprofittechy** [comment]
Here is a possible function signature:

(text_to_copy, copy_button_label, popover_click_to_copy_label, popover_copied_label) (i gave them long names as documentation but feel free to use whatever names you like)

i suggest running the text through the `word()` function like the action_button_html() function does. Although we may end up wanting to use a template to make it translatable, not the word system.

One more thing is that if the input is visible, which I think I prefer, you should be able to manually highlight and copy the text but not alter it.
