### ISSUE TITLE
Make the display_template etc. methods dark mode compatible?

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-ALToolbox#178]
I'm sure we have LOTS of dark mode issues, but if we decide to start supporting dark mode, this is one to fix. I think pretty low priority as we should probably just disable dark mode in most cases right now.

![image](https://github.com/SuffolkLITLab/docassemble-ALToolbox/assets/7645641/f84eef84-6367-4b5c-a782-0837aef4771b)

**Comment by BryceStevenWilley** [comment]
Oh, neat, I didn't know we had made an issue for this. Fixed in #216. I tried fixing the checkbox light background upstream, but it wasn't accepted. The workaround is in https://github.com/jhpyle/docassemble/pull/718#issuecomment-1836994697, which I might push to AssemblyLine proper.
