### ISSUE TITLE
Allow only some inputs on `datatype: BirthDate`

### ISSUE THREAD

**Issue by miabonardi** [SuffolkLITLab/docassemble-ALToolbox#186]
I am working on an abuse prevention order in VT. Sometimes the plaintiff will not know all parts of the defendant's birthday but may know the month, day, or year. Is it possible to add the option to set the `required: False` like this? 

![screen_shot_2023-07-13_at_9 09 55_am_480](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/assets/65858862/a42ab021-caf6-4a48-824d-b7378d02b2a3)

https://github.com/VTskier/docassemble-RFApackage/issues/20

**Comment by BryceStevenWilley** [comment]
It seems like this was fixed upstream with separate fields. I don't think that's something that the Toolbox should take on, so I'm going to close this issue as won't fix
