### ISSUE TITLE
datatype: al_international_phone phone number fields confused some testers

### ISSUE THREAD

**Issue by VTskier** [SuffolkLITLab/docassemble-ALToolbox#201]
In user testing, a couple people have gotten confused by the placeholder text in these **datatype: al_international_phone** phone number fields. They thought they were already filled in. I wonder if having (000) 000-0000 would be better instead of what looks like a real phone number?

**Comment by nonprofittechy** [comment]
Agreed, this has confused me too. @plocket do you know if this is a hardcoded feature or something we can turn off? I know we mostly just adapted an existing library...

**Comment by nonprofittechy** [comment]
I found it--`autoPlaceholder`

https://github.com/jackocnr/intl-tel-input#demo-and-examples

**Comment by plocket** [comment]
https://github.com/jackocnr/intl-tel-input#initialisation-options

**Comment by plocket** [comment]
Reading the docs, AL actually doesn't need to change anything at all. A dev can just set the attribute `hint:` to override the unwanted number. For example, if you want it to appear as if there is no placeholder number, use a space:

```yml
question: |
  Contact info
fields:
  - Your number: phone_number
    datatype: al_international_phone
    hint: " "
```

Made #205 to add this to the demo file

**Comment by nonprofittechy** [comment]
If the hint isn't provided, should and can the default change? I'm not sure the placeholder is ever helpful for people.

**Comment by plocket** [comment]
Do you want me to try to turn it off completely? I believe it's possible.

**Comment by nonprofittechy** [comment]
I think it's worth turning off, yeah. This is the research I've previously seen on this: https://www.nngroup.com/articles/form-design-placeholders/
