### ISSUE TITLE
Change `display_template()` links to green words color with same dotted underline

### ISSUE THREAD

**Issue by miabonardi** [SuffolkLITLab/docassemble-ALToolbox#208]
We saw on usability testing for MOTenantHelp that `display_template()` currently shows as a blue underlined hyperlink (as if a URL) with the only difference being that it has a caret. One user hesitated to click on the template because they thought it would open a new tab and would cause their wifi to be slow.

See https://piccalil.li/tutorial/a-progressive-disclosure-component/

See https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/issues/457

**Comment by miabonardi** [comment]
[9680d23](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/pull/486/commits/9680d233f55e027d4d6680262da25f8c3097734e)

**Comment by miabonardi** [comment]
Is this only supposed to work on collapse_template? I am seeing difference between collapse and display templates

<img width="584" alt="Screen Shot 2023-12-14 at 1 06 32 PM" src="https://github.com/SuffolkLITLab/docassemble-ALToolbox/assets/65858862/1d3a6843-5711-427c-b1bb-fb4fb54c6d36">

**Comment by BryceStevenWilley** [comment]
That wasn't intended, but should be fixed on main now.

**Comment by miabonardi** [comment]
Thank you!!! Looks great.
