### ISSUE TITLE
Is there a way to use `min` or `max` on ThreePartsDate?

### ISSUE THREAD

**Issue by miabonardi** [SuffolkLITLab/docassemble-ALToolbox#211]
https://github.com/SuffolkLITLab/docassemble-ALToolbox/blob/0d88dc9d4d1fc2fa6790c02053c95418bc446b72/docassemble/ALToolbox/ThreePartsDate.py#L917

**Comment by plocket** [comment]
You can use `alMin` and `alMax`: 

https://github.com/SuffolkLITLab/docassemble-ALToolbox/blob/0d88dc9d4d1fc2fa6790c02053c95418bc446b72/docassemble/ALToolbox/data/questions/three_parts_date_demo.yml#L20

https://github.com/SuffolkLITLab/docassemble-ALToolbox/blob/0d88dc9d4d1fc2fa6790c02053c95418bc446b72/docassemble/ALToolbox/data/questions/three_parts_date_demo.yml#L56-L62

https://github.com/SuffolkLITLab/docassemble-ALToolbox/blob/0d88dc9d4d1fc2fa6790c02053c95418bc446b72/docassemble/ALToolbox/data/questions/three_parts_date_demo.yml#L81-L86

**Comment by plocket** [comment]
To answer the question literally, though, currently we don't handle the actual `min` and `max` attributes. It might be possible in js, but not in python. I'm not sure how deep we went down that rabbit hole.

**Comment by nonprofittechy** [comment]
I'm guessing `al_min`/`al_max` will do it for @miabonardi's use case!

**Comment by miabonardi** [comment]
@plocket Thank you! This is great. @nonprofittechy Yes this works!
