### ISSUE TITLE
Demo: `ALAssetList` does not run and runs `ALIncomeList` instead

### ISSUE THREAD

**Issue by miabonardi** [SuffolkLITLab/docassemble-ALToolbox#246]
Think this needs to be `.gathered` instead

https://github.com/SuffolkLITLab/docassemble-ALToolbox/blob/1e2c60c365143895664803e788b366969af6a289/docassemble/ALToolbox/data/questions/al_income_demo.yml#L71-L73

**Comment by nonprofittechy** [comment]
Assets are a subclass of Incomes. I think the display was just throwing you off because the question wasn't as customized as it could be.
