### ISSUE TITLE
Add a business day function to help with date math

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-ALToolbox#41]
Should use the `holidays` Python module as well as accounting for Saturday and Sunday

**Comment by nonprofittechy** [comment]
For very short time periods, the math can be more complicated. E.g., in many jurisdictions, if it's less than 7 days, you only count the business days. If it's more than 7 days, you just worry about the ending day.

This will be a wrapper around an existing module--something like https://github.com/gocardless/business-python or http://wilsonfreitas.github.io/python-bizdays/.

Investigate whether we really need a wrapper

**Comment by purplesky2016** [comment]
Can you give an example of how this function should work?

**Comment by nonprofittechy** [comment]
@purplesky2016 it would be something like this:

get_business_day(date, days=14, country_code=US, state=MA) and then it would tell you the next business day that is at least 14 days later. The special wrinkle is that in many states, there is a minimum number of days where every day needs to be a business day instead of just the ending day. I think it would make sense for that to be a parameter too.

This should also incorporate state holidays, and the `holidays` Python package is a good solution for that. I used that code in MADE which is here: https://github.com/GBLS/docassemble-MAEvictionDefense/blob/057d0178c83e964ce9e9361c702653a9d1b81049/docassemble/MAEvictionDefense/data/questions/eviction.code.yml#L398

The one funny thing about the holidays package is that it calls Evacuation Day a holiday, but that's no longer a day courts or businesses are closed in MA.
