### ISSUE TITLE
Create a function that makes a `template` into a block that can be clicked on to copy to clipboard

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-ALToolbox#42]
This is different from copy_share_button because it's for a longer block of text that isn't editable.

**Comment by purplesky2016** [comment]
Do you want a separate function or to expand the existing copy_share_button module? From user perspective it might be better to use the same function for both purposes.

**Comment by purplesky2016** [comment]
I'll investigate.
