### ISSUE TITLE
Use `var` in review_widget.js, not let

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-ALToolbox#98]
Very good point, probably should have used `var`. TBF I'm not sure if everything else we do / docassemble / bootstrap does supports IE < 11, but it would be silly if everything else is fine but not this.

_Originally posted by @BryceStevenWilley in https://github.com/SuffolkLITLab/docassemble-ALToolbox/pull/86#discussion_r957812867_

**Comment by nonprofittechy** [comment]
I think I made this point to @plocket 2 years ago, but things have changed a bit.

According to our analytics, we haven't had any visits from IE in the period I checked--from May 2022 through today.

![image](https://user-images.githubusercontent.com/7645641/189218393-8aa0ffb5-af6d-4b9f-b3d0-2597daed2734.png)

Now that Tyler's EFM doesn't require IE, our major partner, the appeals court, no longer is forced to use IE either. So it may not be worth putting more energy into this--but good eye @plocket.

Hopefully this can let us use more idiomatic JS syntax across our frontend stuff.
